version: '3'
services:
  php:
    container_name: php
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:80'
    volumes:
      - ../:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      #- ./db_mysql:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: php-db